### ISSUE TITLE
Add User Authentication Feature in Django

### ISSUE THREAD

**Issue by miikkuu** [miikkuu/django-url-shortener#2]
for our small django app, try if you can implement some basic user auth and registration stuff on django . Do reach out if you need help.

**Comment by jadentel** [comment]
Hi,
Do you want a different page that does authentication on SQL and then allows the user to shorten the URL or can the user shorten the url without logging in?

**Comment by miikkuu** [comment]
@jadentel  Hey there! yeah , the latter can work. My thoughts were that the user is allowed to shorten links and then if he chooses to sign/login then the user will be able to view all his links on the main page (maybe in a sidebar ). Do you get the idea? 
You are free to improvise . 
Reach me out if you need help :)

**Comment by VidyaYadavv1519** [comment]
Hii 
I want to try this can you assign me ??

**Comment by miikkuu** [comment]
@VidyaYadavv1519 Hello Vidya ! The Issue is already solved. You can look at this one #4 .
Let me know if you are intrested in it and I will assign you.
